### ISSUE TITLE
Extreme lag while trying another translate

### ISSUE THREAD

**Issue by yumiowari** [pop4959/Bolt#142] opened 2024-06-14 19:05 UTC
I downloaded this translation for Bolt and when selected it made the game unplayable (can't login, etc.).
[pt_BR.zip](https://github.com/user-attachments/files/15842493/pt_BR.zip)

**Comment by pop4959** [comment] 2024-06-15 02:51
Closing since there is no reproduction steps or profile included in this issue, as is required for reporting a performance issue. Please join the Discord server for support if you need help troubleshooting this issue.

**Closed by pop4959** 2024-06-15 02:51 UTC
Labels: invalid

**Comment by yumiowari** [comment] 2024-06-15 05:02
Sorry, i didn't knew about it.

However, the issue is what I said. Simply after changing the lang to pt_BR
(which I found in your Github docs about Bolt) the server started but it
was unplayable! These are the steps.

Being technical, although I could login, after a few seconds I lost
comnection and it appeared in server bash as if I was still online.

I host my project in a VM at Google Cloud running the latest Paper server.

Em sex., 14 de jun. de 2024 23:51, pop4959 ***@***.***>
escreveu:

**Comment by pop4959** [comment] 2024-06-15 05:31
Please at least provide a spark profile, or join the Discord for help troubleshooting.

Changing the language should not affect anything, so it is unlikely a bug with that translation specifically.

**Comment by yumiowari** [comment] 2024-06-15 14:40
Ok, I will do that.

Em sáb., 15 de jun. de 2024 02:31, pop4959 ***@***.***>
escreveu:
