### ISSUE TITLE
Armor stand matching not run from Entity scheduler on Folia

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [pop4959/Bolt#37] opened 2023-04-23 15:51 UTC
I think this is not your plugin's err, but I still want to share this Err whit you ;)

https://paste.ubuntu.com/p/k8k4MxPKwq/

I added some datapacks to the world folder, which I know is very irrational in Folia, which can cause a lot of problems, but I still want to check with you if the problem is caused by the packets

This is datepacks:
![image](https://user-images.githubusercontent.com/71379165/233850099-2a5aec90-276e-42b2-baf6-6017b2ed922e.png)

**Comment by xiaoyueyoqwq** [comment] 2023-04-23 15:52
By the way, the reason I only provide these errors is that the server keeps repeating this error, not that I don't want to provide more :(

**Comment by pop4959** [comment] 2023-04-23 16:01
Yes this is a bug with Bolt on Folia, because BlockFromTo runs on the region scheduler but armor stand marching should be scheduled onto the entity scheduler.

I am not able to fix this right now, as I don't have access to a computer until May 1st. For now, the best solution would be to ignore the error or disable armor stand protections in the config (which will disable that matcher).

**Comment by xiaoyueyoqwq** [comment] 2023-04-23 16:10
> Yes this is a bug with Bolt on Folia, because BlockFromTo runs on the region scheduler but armor stand marching should be scheduled onto the entity scheduler.
> 
> I am not able to fix this right now, as I don't have access to a computer until May 1st. For now, the best solution would be to ignore the error or disable armor stand protections in the config (which will disable that matcher).

I sympathize with you because I have also been through ;)
I think if you want we can work on the Folia core and apply it to productivity environments, you know, single-threaded operations on Minecraft servers are one of the big reasons for server lag, and I'm also plagued by this issue :(
And I'm trying to make this a reality, just as fabric went from non-mainstream to the best Minecraft game client, that's really cool isn't it haha ;)

**Comment by pop4959** [comment] 2023-04-23 16:25
I understand. Folia support for Bolt is new, as is the plugin itself so please report any issues you find. I will fix them at my earliest convenience.

**Comment by xiaoyueyoqwq** [comment] 2023-04-23 16:36
> I understand. Folia support for Bolt is new, as is the plugin itself so please report any issues you find. I will fix them at my earliest convenience.

Of course, I'd love to keep track of issues
By the way, I hope this plugin can add a feature similar to BlockLocker: using the sign to lock blocks like chest or other things, which I think is faster and easier than learning how to use instructions, and is more friendly for new players, I hope you will adopt :)

**Comment by pop4959** [comment] 2023-04-23 16:39
Bolt has auto protect support which is easier and does not require signs. There are no plans to add signs, if you want that you should use BlockLocker instead.

**Comment by xiaoyueyoqwq** [comment] 2023-04-24 04:03
> Bolt has auto protect support which is easier and does not require signs. There are no plans to add signs, if you want that you should use BlockLocker instead.

Then I will consider turning on automatic protection and finally express my sincerest thanks to you :)

**Comment by pop4959** [comment] 2023-04-24 04:07
Re-opening this issue as the bug mentioned here has not been fixed yet.

**Comment by pop4959** [comment] 2023-05-02 06:01
This doesn't seem to happen on the latest version of Folia after some testing.

Closing for now, but if this surfaces again with proper reproduction steps I will take another look. For now it looks like things are working.

**Closed by pop4959** 2023-05-02 06:01 UTC
Labels: bug
